### ISSUE TITLE
Error on Youtube Lives

### ISSUE THREAD

**Issue by L30nard0100b** [KevinBytesTheDust/CVAmp#303]
- CVAmp version? 0.7.1
- OS with version? win11
- Streaming platform? youtube.com
- Proxies from webshare.io? yes

Bug:

After a while all the bots watching a live gets an error: "an error occured. refresh or try again later".
If you manually refresh the instance the bots keep watching the live for a while and then the same error occurs.
(i tried different user agents, my own connection without any proxy and auto restart but the same error occurs)
An "auto refresh" every x seconds can solve this problem.

Screenshot:
![20240902_155716_instance6](https://github.com/user-attachments/assets/47571b08-ab64-43bc-b01b-9161df76cd5e)

Logs:
2024-09-02 16:05:47,403;INFO;26_23;MainThread;manager;__init__;Manager start on Windows-10-10.0.22631-SP0
2024-09-02 16:05:54,316;INFO;0_23;Thread-2 (spawn_instance_thread);manager;spawn_instance_thread;Ordered YOUTUBE instance 1, Thread-2 (spawn_instance_thread), proxy http://45.151.162.198:6600
2024-09-02 16:05:54,318;INFO;0_23;Thread-2 (spawn_instance_thread);manager;instance_status_report_callback;STARTING instance 1
2024-09-02 16:05:56,319;INFO;0_23;Thread-3 (spawn_instance_thread);manager;spawn_instance_thread;Ordered YOUTUBE instance 2, Thread-3 (spawn_instance_thread), proxy http://64.64.118.149:6732
2024-09-02 16:05:56,321;INFO;0_23;Thread-3 (spawn_instance_thread);manager;instance_status_report_callback;STARTING instance 2
2024-09-02 16:05:58,322;INFO;0_24;Thread-4 (spawn_instance_thread);manager;spawn_instance_thread;Ordered YOUTUBE instance 3, Thread-4 (spawn_instance_thread), proxy http://206.41.172.74:6634
2024-09-02 16:05:58,325;INFO;3_24;Thread-4 (spawn_instance_thread);manager;instance_status_report_callback;STARTING instance 3
2024-09-02 16:06:03,151;WARNING;1_25;Thread-2 (spawn_instance_thread);instance;goto_with_retry;Instance 1 failed connection attempt #1.
2024-09-02 16:06:03,414;WARNING;1_25;Thread-2 (spawn_instance_thread);instance;goto_with_retry;Instance 1 failed connection attempt #2.
2024-09-02 16:06:08,325;INFO;0_25;Thread-6 (spawn_instance_thread);manager;spawn_instance_thread;Ordered YOUTUBE instance 4, Thread-6 (spawn_instance_thread), proxy http://38.154.227.167:5868
2024-09-02 16:06:08,328;INFO;0_25;Thread-6 (spawn_instance_thread);manager;instance_status_report_callback;STARTING instance 4
2024-09-02 16:06:10,329;INFO;0_25;Thread-7 (spawn_instance_thread);manager;spawn_instance_thread;Ordered YOUTUBE instance 5, Thread-7 (spawn_instance_thread), proxy http://173.0.9.70:5653
2024-09-02 16:06:10,332;INFO;0_25;Thread-7 (spawn_instance_thread);manager;instance_status_report_callback;STARTING instance 5
2024-09-02 16:06:11,175;WARNING;1_26;Thread-2 (spawn_instance_thread);instance;goto_with_retry;Instance 1 failed connection attempt #3.
2024-09-02 16:06:11,178;ERROR;0_26;Thread-2 (spawn_instance_thread);instance;start;net::ERR_TIMED_OUT at https://www.youtube.com/ died at page chrome-error://chromewebdata/
Traceback (most recent call last):
  File "cvamp\instance.py", line 86, in start
  File "cvamp\sites.py", line 148, in todo_after_spawn
  File "cvamp\instance.py", line 159, in goto_with_retry
  File "playwright\sync_api\_generated.py", line 9327, in goto
  File "playwright\_impl\_sync_base.py", line 115, in _sync
  File "playwright\_impl\_page.py", line 484, in goto
  File "playwright\_impl\_frame.py", line 149, in goto
  File "playwright\_impl\_connection.py", line 63, in send
  File "playwright\_impl\_connection.py", line 495, in wrap_api_call
  File "playwright\_impl\_connection.py", line 101, in inner_send
playwright._impl._errors.Error: net::ERR_TIMED_OUT at https://www.youtube.com/
2024-09-02 16:06:11,185;INFO;25_26;Thread-2 (spawn_instance_thread);manager;instance_status_report_callback;SHUTDOWN instance 1
2024-09-02 16:06:11,486;WARNING;1_25;Thread-3 (spawn_instance_thread);sites;todo_after_spawn;Cookie consent banner not found/clicked.
2024-09-02 16:06:12,332;INFO;0_26;Thread-8 (spawn_instance_thread);manager;spawn_instance_thread;Ordered YOUTUBE instance 6, Thread-8 (spawn_instance_thread), proxy http://204.44.69.89:6342
2024-09-02 16:06:12,335;INFO;0_26;Thread-8 (spawn_instance_thread);manager;instance_status_report_callback;STARTING instance 6
2024-09-02 16:06:12,631;WARNING;1_26;Thread-4 (spawn_instance_thread);sites;todo_after_spawn;Cookie consent banner not found/clicked.
2024-09-02 16:06:19,260;INFO;2_28;Thread-3 (spawn_instance_thread);manager;instance_status_report_callback;INITIALIZED instance 2
2024-09-02 16:06:25,681;WARNING;1_28;Thread-7 (spawn_instance_thread);sites;todo_after_spawn;Cookie consent banner not found/clicked.
2024-09-02 16:06:29,390;INFO;2_28;Thread-3 (spawn_instance_thread);manager;instance_status_report_callback;WATCHING instance 2
2024-09-02 16:06:32,126;WARNING;2_28;Thread-6 (spawn_instance_thread);sites;todo_after_spawn;Cookie consent banner not found/clicked.
2024-09-02 16:06:33,542;INFO;2_28;Thread-7 (spawn_instance_thread);manager;instance_status_report_callback;INITIALIZED instance 5
2024-09-02 16:06:39,910;WARNING;2_28;Thread-8 (spawn_instance_thread);sites;todo_after_spawn;Cookie consent banner not found/clicked.
2024-09-02 16:06:43,670;INFO;2_28;Thread-7 (spawn_instance_thread);manager;instance_status_report_callback;WATCHING instance 5
2024-09-02 16:06:44,724;ERROR;2_28;Thread-4 (spawn_instance_thread);instance;start;Timeout 30000ms exceeded. died at page https://www.youtube.com/live/******
Traceback (most recent call last):
  File "cvamp\instance.py", line 86, in start
  File "cvamp\sites.py", line 163, in todo_after_spawn
  File "playwright\sync_api\_generated.py", line 8349, in wait_for_selector
  File "playwright\_impl\_sync_base.py", line 115, in _sync
  File "playwright\_impl\_page.py", line 357, in wait_for_selector
  File "playwright\_impl\_frame.py", line 327, in wait_for_selector
  File "playwright\_impl\_connection.py", line 63, in send
  File "playwright\_impl\_connection.py", line 495, in wrap_api_call
  File "playwright\_impl\_connection.py", line 101, in inner_send
playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.
2024-09-02 16:06:44,730;INFO;0_28;Thread-4 (spawn_instance_thread);manager;instance_status_report_callback;SHUTDOWN instance 3
2024-09-02 16:06:57,341;INFO;1_27;Thread-8 (spawn_instance_thread);manager;instance_status_report_callback;INITIALIZED instance 6
2024-09-02 16:06:59,756;INFO;1_27;Thread-3 (spawn_instance_thread);manager;instance_status_report_callback;BUFFERING instance 2
2024-09-02 16:07:07,472;INFO;1_27;Thread-8 (spawn_instance_thread);manager;instance_status_report_callback;WATCHING instance 6
2024-09-02 16:07:07,609;ERROR;1_27;Thread-6 (spawn_instance_thread);instance;start;Timeout 30000ms exceeded. died at page https://www.youtube.com/live/******
Traceback (most recent call last):
  File "cvamp\instance.py", line 86, in start
  File "cvamp\sites.py", line 163, in todo_after_spawn
  File "playwright\sync_api\_generated.py", line 8349, in wait_for_selector
  File "playwright\_impl\_sync_base.py", line 115, in _sync
  File "playwright\_impl\_page.py", line 357, in wait_for_selector
  File "playwright\_impl\_frame.py", line 327, in wait_for_selector
  File "playwright\_impl\_connection.py", line 63, in send
  File "playwright\_impl\_connection.py", line 495, in wrap_api_call
  File "playwright\_impl\_connection.py", line 101, in inner_send
playwright._impl._errors.TimeoutError: Timeout 30000ms exceeded.
2024-09-02 16:07:07,615;INFO;0_27;Thread-6 (spawn_instance_thread);manager;instance_status_report_callback;SHUTDOWN instance 4
2024-09-02 16:07:14,033;INFO;1_26;Thread-7 (spawn_instance_thread);manager;instance_status_report_callback;BUFFERING instance 5
2024-09-02 16:07:30,193;INFO;1_26;Thread-3 (spawn_instance_thread);instance;start;ENDED: instance 2
2024-09-02 16:07:30,198;INFO;0_26;Thread-3 (spawn_instance_thread);manager;instance_status_report_callback;SHUTDOWN instance 2
2024-09-02 16:07:34,284;INFO;1_25;Thread-7 (spawn_instance_thread);instance;start;ENDED: instance 5
2024-09-02 16:07:34,290;INFO;0_25;Thread-7 (spawn_instance_thread);manager;instance_status_report_callback;SHUTDOWN instance 5
2024-09-02 16:07:37,839;INFO;1_24;Thread-8 (spawn_instance_thread);manager;instance_status_report_callback;BUFFERING instance 6
2024-09-02 16:07:37,841;INFO;0_24;Thread-8 (spawn_instance_thread);instance;start;ENDED: instance 6
2024-09-02 16:07:37,846;INFO;0_24;Thread-8 (spawn_instance_thread);manager;instance_status_report_callback;SHUTDOWN instance 6

**Comment by KevinBytesTheDust** [comment]
Hi there. Can you check the “error” stats on the webshare website? Refreshing might work, but it will cost a lot of CPU and doesn't solve the real cause. It's better to find the real cause, like bandwidth, proxy or hardware usage.

**Comment by L30nard0100b** [comment]
hi, thanks for your patience the error that im getting is "high_concurrency", i can not open more than 3 tabs.
I also noticed that youtube sometimes flag me:
![bot](https://github.com/user-attachments/assets/fb2e4b82-0cff-494d-89c6-aa010d7a09b0)
(it says: login to prove that you are an human)

**Comment by KevinBytesTheDust** [comment]
You can purchase the high_concurrency option on webshare, which could help.

I've never seen the message about youtube being blocked, I'll keep an eye on it - and whether I can do anything about it or if it's just showing up because of the proxy.

**Comment by johnxdifu** [comment]
what does high concurrency help with?

**Comment by gotspritedude** [comment]
If it helps at all, I’ve been encountering the same issue, where the headon window shows that youtube requires a log in to prove that it is a human

proxies are from a webshare subscription with the high concurrency option
